### PR TITLE
Generate Article scaffold

### PR DESCRIPTION
**Pull request by philipd97**
**Show how `CRUD` in Rails works by generating scaffold**
- using `rails generate scaffold Article title:string description:text` command to generate Article resources
- scaffold generates model, database migration, controller and view for the particular model
- using `rails db:migrate` to create the database
- schema & file is generated
- view the routes available using `rails routes --expanded`
- interact with the generated model

### CODE REVIEW

**Review by tlkiong — CHANGES_REQUESTED** [review]
1. Is this just a scaffold or is this also some styling and codes?
2. Indent your scss properly

---

If its more than just scaffold, I wont review this. Ask yourself. Do you want to review so many files when most of it is generated?

**Comment by philipd97** [comment]
> 1. Is this just a scaffold or is this also some styling and codes?
> 2. Indent your scss properly
> 
> If its more than just scaffold, I wont review this. Ask yourself. Do you want to review so many files when most of it is generated?

Just `schema.rb` is belongs to `rails db:migrate`  while all the others are generated by scaffold. Overall all are generated.

**Comment by tlkiong** [comment]
If everything is scaffold, I don't need to review. Since none is your code.

**Comment by philipd97** [comment]
So I just directly merge this PR?

**Comment by tlkiong** [comment]
yes

**Pull request merged**
