### PR TITLE
Using of Hashes (Section 2)

### PR DESCRIPTION
**Pull request by philipd97**

### CODE REVIEW

**Review by tlkiong — CHANGES_REQUESTED** [review]
1. Whats the difference between symbol & string?
2. If we have a hash: 

```
hash_1 = { "x" => 1 }
hash_2 = { y: 2 }
```
What happens if we do:

```
puts hash_1[:x]
puts hash_2["y"]
```

**Comment by philipd97** [comment]
> 1. Whats the difference between symbol & string?
> 2. If we have a hash:
> 
> ```
> hash_1 = { "x" => 1 }
> hash_2 = { y: 2 }
> ```
> 
> What happens if we do:
> 
> ```
> puts hash_1[:x]
> puts hash_2["y"]
> ```

1. `Symbol` are immutable which means the value can't be change, while `String` can be change. Usually `Symbol` is used if we want the variable to be unique.

2. It will prints out empty representing nil, since both hash doesn't contain the particular key `:x for hash_1` and `"y" for hash_2`

**Comment by tlkiong** [comment]
> Symbol are immutable which means the value can't be change, while String can be change. Usually Symbol is used if we want the variable to be unique.

This don't make any sense in the context of hash. If you change the key which is in string, it will refer to a new key. So, in effect, both can't be changed anyway

**Comment by philipd97** [comment]
> This don't make any sense in the context of hash. If you change the key which is in string, it will refer to a new key. So, in effect, both can't be changed anyway

I see, so for Hash key, is it preferable to use Symbol or String as the key?

**Comment by tlkiong** [comment]
That is my question. To decide which is preferable, you need to know the difference. So, what are the differences?

**Comment by philipd97** [comment]
> That is my question. To decide which is preferable, you need to know the difference. So, what are the differences?

Symbol is preferable for Hash key due to it's nature of memory allocated for them only once & stored, making them faster compared to Hash with String keys

**Comment by tlkiong** [comment]
> memory allocated for them only once & stored, making them faster compared to Hash with String keys

huh? Are you implying memory allocated for string is not only once & stored? huh???

**Comment by philipd97** [comment]
> That is my question. To decide which is preferable, you need to know the difference. So, what are the differences?

Sorry for the misleading answer, let me answer the question again.

`Symbol` is preferred due to it's nature of having the same `object_id` once created & and reuse it in the code. And when doing hash computing, like comparison, hash would just need to uses the `object_id` of the Symbol key to do the comparison. 

While for String, the hash would have to look on the String key used and compare if it is the same with the key used. Which would takes up more time.

**Comment by tlkiong** [comment]
Speak english please.

**Comment by philipd97** [comment]
Since `String` is mutable & `Symbol` is immutable, when using `String` as a Hash Key, Ruby will turn the `String` into frozen string for Hash Key. Which it will have to treat String differently when used as Hash Key, for `Symbol` since it is immutable, Ruby doesn't have to go extra step for it.

**Comment by tlkiong** [comment]
no.
See this:
image

As long as a symbol is the same value, it is from the same location in memory. Which means
1. if `:symbol` don't exist in memory, allocate memory for it
2. if `:symbol` exist in memory, fetch it

VS
Strings:
1. `"symbol"` <= add this to memory
2.`"symbol"` <= add this to memory
In the end, for symbol, only 1 memory slot is allocated for the same "value" while for string, it'll be 2 slots. It might not see like much but in a big system where a lot of these are used, it will add up. Hence, symbols are preferable.

**Comment by tlkiong** [comment]
Next question:
```
hash_1 = { "x" => 1 }
```

How can I do it so that I can do:
```
puts hash_1[:x]
# 1
```

**Comment by philipd97** [comment]
> no.
> See this:
> image
> 
> As long as a symbol is the same value, it is from the same location in memory. Which means
> 
> 1. if `:symbol` don't exist in memory, allocate memory for it
> 2. if `:symbol` exist in memory, fetch it
> 
> VS
> Strings:
> 
> 1. `"symbol"` <= add this to memory
>    2.`"symbol"` <= add this to memory
>    In the end, for symbol, only 1 memory slot is allocated for the same "value" while for string, it'll be 2 slots. It might not see like much but in a big system where a lot of these are used, it will add up. Hence, symbols are preferable.

So for accessing the Hash Key, it does so by comparing the object_id then check if it's the same?

**Comment by philipd97** [comment]
> Next question:
> 
> ```
> hash_1 = { "x" => 1 }
> ```
> 
> How can I do it so that I can do:
> 
> ```
> puts hash_1[:x]
> # 1
> ```

I would change the hash_1 key to symbol by doing so:

image

**Comment by tlkiong** [comment]
> So for accessing the Hash Key, it does so by comparing the object_id then check if it's the same?

kind of.

>I would change the hash_1 key to symbol by doing so:

In rails, you can just do:
```
hash_1.with_indifferent_access[:x]
```

**Review by tlkiong — APPROVED** [review]

**Comment by philipd97** [comment]
> kind of.

I see, so for like String key, it uses other way to access it?

> In rails, you can just do:
>
> `hash_1.with_indifferent_access[:x]`

Ok, will take note on it.

**Review by LeeRenJie — APPROVED** [review]

**Pull request merged**
