### PR TITLE
Overview on Comparison (Section 2)

### PR DESCRIPTION
**Pull request by philipd97**

### CODE REVIEW

**Review by tlkiong — CHANGES_REQUESTED** [review]
How about `<=>`?
*aka, the spaceship operator

**Comment by philipd97** [comment]
> How about `<=>`?
> *aka, the spaceship operator

The instructor didn't show this operator 😮, will check it out & add in 👍

**Comment by tlkiong** [comment]
> > How about `<=>`?
> > *aka, the spaceship operator
> 
> The instructor didn't show this operator 😮, will check it out & add in 👍

I know the instructor didn't show. Don't have to be so defensive. I'm here to make you aware of these stuffs which you normally don't learn in courses but use in real world situation.

**Review by tlkiong — CHANGES_REQUESTED** [review]
When we use spaceship operator?

**Comment by philipd97** [comment]
> When we use spaceship operator?

Usually to `.sort` an array which consist of own class, as the `.sort` doesn't support sorting of user defined class.

**Review by tlkiong — APPROVED** [review]

**Review by LeeRenJie — APPROVED** [review]

**Pull request merged**
